- name: Install resolvconf requirements
  ansible.builtin.apt:
    name: resolvconf
    state: present

# noqa: risky-file-permissions
- name: Update resolvconf to use local name server
  ansible.builtin.lineinfile:
    line: "name_servers=127.0.0.1"
    dest: /etc/resolvconf.conf
    regexp: "^#?name_servers="
    create: true
  notify: regenerate resolvconf
